name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cleanup potential bad lock/content
        run: |
          rm -rf node_modules || true
          rm -f package-lock.json || true
      - name: Diagnostics
        run: |
          node -v
          npm -v
          echo 'Workspace files:'
          ls -la
      - name: Install
        run: npm install --no-optional --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
